### PR TITLE
Adding preserve unknown fileds to support parameters as a map

### PR DESCRIPTION
**Pull request by adusumillipraveen**
- See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning

### CODE REVIEW

**Comment by duanhongyi** [comment]
LGTM

**Review by dee0sap — COMMENTED** [review]
Hello
I think this is the list of files that need to be changed
clusterserviceclass.yaml
clusterserviceplan.yaml
servicebinding.yaml
serviceclass.yaml
serviceinstance.yaml
serviceplan.yaml

Also I think they might be machine generated.   If that is correct then the script that generates them probably needs updating.

**Comment by duanhongyi** [comment]
OK, I'll take a closer look tomorrow.

**Comment by duanhongyi** [comment]
> Hello I think this is the list of files that need to be changed clusterserviceclass.yaml clusterserviceplan.yaml servicebinding.yaml serviceclass.yaml serviceinstance.yaml serviceplan.yaml
> 
> Also I think they might be machine generated. If that is correct then the script that generates them probably needs updating.

It seems that only serviceinstance.yaml(parameters) and servicebinding.yaml(parameters) need to be changed.

Can you explain why you need to change these.
@dee0sap

**Comment by duanhongyi** [comment]
> Sure. List below shows attributes of these classes that will be dropped if the don't have 'x-kubernetes-preserve-unknown-fields: true' clusterserviceclass and serviceclass : defaultProvisionParameters and externalMetadata
> 
> clusterservicepland and serviceplan: defaultProvisionParameters, externalMetadata, instanceCreateParameterSchema, instanceUpdateParameterSchema, and serviceBindingCreateParameterSchema

Thank you very much, because these attributes are not used in my project, so I don't know them very well.

**Comment by duanhongyi** [comment]
@dee0sap 
I will submit a PR tomorrow. Please check it for me. Thank you very much.

**Comment by dee0sap** [comment]
You're welcome and thank you @duanhongyi for doing this.

I wanted to do something but my schedule has just been too full.

**Pull request merged**
